// packages/fhevm-sdk/src/universal/adapters/vue/DecryptionComponent.vue
<!-- Reusable Vue component for FHE decryption -->

<template>
  <div class="decryption-component">
    <h3>FHE Decryption</h3>
    <div>
      <button
        @click="handleDecrypt"
        :disabled="isDecrypting || status !== 'ready' || !handle"
      >
        {{ isDecrypting ? "Decrypting..." : "Decrypt" }}
      </button>
    </div>
    <div v-if="decryptedValue !== null">
      <p>Decrypted Value: {{ String(decryptedValue) }}</p>
    </div>
    <div v-if="status === 'error'" class="error">
      <p>Error: {{ error?.message }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useUniversalFhevm } from './useUniversalFhevm';

// Props
const props = defineProps<{
  provider: string | object | undefined;
  chainId: number;
  handle: any;
  userAddress: string;
}>();

const emit = defineEmits<{
  (e: 'decrypted', value: any): void;
}>();

// FHEVM instance
const { instance, status, error } = useUniversalFhevm({
  provider: props.provider,
  chainId: props.chainId,
  enabled: true
});

// Reactive state
const decryptedValue = ref<any>(null);
const isDecrypting = ref<boolean>(false);

// Methods
const handleDecrypt = async () => {
  if (!instance.value || !props.handle) return;
  
  try {
    isDecrypting.value = true;
    // @ts-ignore
    const value = await instance.value.decrypt(props.handle, props.userAddress, props.provider);
    decryptedValue.value = value;
    emit('decrypted', value);
  } catch (err) {
    console.error("Decryption failed:", err);
  } finally {
    isDecrypting.value = false;
  }
};
</script>

<style scoped>
.decryption-component {
  padding: 1rem;
  border: 1px solid #ccc;
  border-radius: 4px;
}

.error {
  color: red;
  margin-top: 1rem;
}

button {
  margin: 0.5rem;
  padding: 0.5rem;
}
</style>

// packages/fhevm-sdk/src/universal/adapters/react/DecryptionComponent.tsx
// Reusable React component for FHE decryption

import React, { useState } from "react";
import { useUniversalFhevm } from "./useUniversalFhevm";

interface DecryptionComponentProps {
  provider: string | object | undefined;
  chainId: number;
  handle: any;
  userAddress: string;
  onDecrypted?: (value: any) => void;
}

const DecryptionComponent: React.FC<DecryptionComponentProps> = (props: DecryptionComponentProps) => {
  const { provider, chainId, handle, userAddress, onDecrypted } = props;
  
  const { instance, status, error } = useUniversalFhevm({
    provider,
    chainId,
    enabled: true
  });
  
  const [decryptedValue, setDecryptedValue] = useState<any>(null);
  const [isDecrypting, setIsDecrypting] = useState<boolean>(false);
  
  const handleDecrypt = async () => {
    if (!instance || !handle) return;
    
    try {
      setIsDecrypting(true);
      // @ts-ignore
      const value = await instance.decrypt(handle, userAddress, provider);
      setDecryptedValue(value);
      if (onDecrypted) {
        onDecrypted(value);
      }
    } catch (err) {
      console.error("Decryption failed:", err);
    } finally {
      setIsDecrypting(false);
    }
  };
  
  if (status === "error") {
    return (
      <div className="error">
        <p>Error: {error?.message}</p>
      </div>
    );
  }
  
  return (
    <div className="decryption-component">
      <h3>FHE Decryption</h3>
      <div>
        <button
          onClick={handleDecrypt}
          disabled={isDecrypting || status !== "ready" || !handle}
        >
          {isDecrypting ? "Decrypting..." : "Decrypt"}
        </button>
      </div>
      {decryptedValue !== null && (
        <div>
          <p>Decrypted Value: {String(decryptedValue)}</p>
        </div>
      )}
    </div>
  );
};

export default DecryptionComponent;
