// packages/fhevm-sdk/src/universal/adapters/vue/EncryptionComponent.vue
<!-- Reusable Vue component for FHE encryption -->

<template>
  <div class="encryption-component">
    <h3>FHE Encryption</h3>
    <div>
      <input
        v-model="inputValue"
        type="number"
        placeholder="Enter a number to encrypt"
        :disabled="isEncrypting || status !== 'ready'"
      />
      <button
        @click="handleEncrypt"
        :disabled="isEncrypting || status !== 'ready' || !inputValue"
      >
        {{ isEncrypting ? "Encrypting..." : "Encrypt" }}
      </button>
    </div>
    <div v-if="encryptedHandle">
      <p>Encrypted Handle: {{ JSON.stringify(encryptedHandle) }}</p>
    </div>
    <div v-if="status === 'error'" class="error">
      <p>Error: {{ error?.message }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useUniversalFhevm } from './useUniversalFhevm';

// Props
const props = defineProps<{
  provider: string | object | undefined;
  chainId: number;
}>();

const emit = defineEmits<{
  (e: 'encrypted', handle: any): void;
}>();

// FHEVM instance
const { instance, status, error } = useUniversalFhevm({
  provider: props.provider,
  chainId: props.chainId,
  enabled: true
});

// Reactive state
const inputValue = ref<string>('');
const encryptedHandle = ref<any>(null);
const isEncrypting = ref<boolean>(false);

// Methods
const handleEncrypt = async () => {
  if (!instance.value || !inputValue.value) return;
  
  try {
    isEncrypting.value = true;
    // @ts-ignore
    const handle = await instance.value.encryptUInt32(Number(inputValue.value));
    encryptedHandle.value = handle;
    emit('encrypted', handle);
  } catch (err) {
    console.error("Encryption failed:", err);
  } finally {
    isEncrypting.value = false;
  }
};
</script>

<style scoped>
.encryption-component {
  padding: 1rem;
  border: 1px solid #ccc;
  border-radius: 4px;
}

.error {
  color: red;
  margin-top: 1rem;
}

input, button {
  margin: 0.5rem;
  padding: 0.5rem;
}
</style>

// packages/fhevm-sdk/src/universal/adapters/react/EncryptionComponent.tsx
// Reusable React component for FHE encryption

import React, { useState } from "react";
import { useUniversalFhevm } from "./useUniversalFhevm";

interface EncryptionComponentProps {
  provider: string | object | undefined;
  chainId: number;
  onEncrypted?: (handle: unknown) => void;
}

const EncryptionComponent: React.FC<EncryptionComponentProps> = (props: EncryptionComponentProps) => {
  const { provider, chainId, onEncrypted } = props;
  const { instance, status, error } = useUniversalFhevm({
    provider,
    chainId,
    enabled: true
  });
  
  const [inputValue, setInputValue] = useState<string>("");
  const [encryptedHandle, setEncryptedHandle] = useState<any>(null);
  const [isEncrypting, setIsEncrypting] = useState<boolean>(false);
  
  const handleEncrypt = async () => {
    if (!instance || !inputValue) return;
    
    try {
      setIsEncrypting(true);
      // @ts-ignore
      const handle = await instance.encryptUInt32(Number(inputValue));
      setEncryptedHandle(handle);
      if (onEncrypted) {
        onEncrypted(handle);
      }
    } catch (err) {
      console.error("Encryption failed:", err);
    } finally {
      setIsEncrypting(false);
    }
  };
  
  if (status === "error") {
    return (
      <div className="error">
        <p>Error: {error?.message}</p>
      </div>
    );
  }
  
  return (
    <div className="encryption-component">
      <h3>FHE Encryption</h3>
      <div>
        <input
          type="number"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          placeholder="Enter a number to encrypt"
          disabled={isEncrypting || status !== "ready"}
        />
        <button
          onClick={handleEncrypt}
          disabled={isEncrypting || status !== "ready" || !inputValue}
        >
          {isEncrypting ? "Encrypting..." : "Encrypt"}
        </button>
      </div>
      {encryptedHandle && (
        <div>
          <p>Encrypted Handle: {JSON.stringify(encryptedHandle)}</p>
        </div>
      )}
    </div>
  );
};

export default EncryptionComponent;
