// examples/universal-react-example.tsx
// Universal FHEVM SDK React Example

import React, { useState } from "react";
import { react } from "@fhevm-sdk/universal";

const UniversalReactExample: React.FC = () => {
  const [inputValue, setInputValue] = useState<string>("");
  const [encryptedHandle, setEncryptedHandle] = useState<any>(null);
  const [decryptedValue, setDecryptedValue] = useState<any>(null);
  
  // FHEVM instance
  const { instance, status, error } = react.useUniversalFhevm({
    provider: typeof window !== 'undefined' ? (window as any).ethereum : undefined,
    chainId: 11155111, // Sepolia testnet
    enabled: true,
  });

  // Encryption handler
  const handleEncrypt = async () => {
    if (!instance || !inputValue) return;
    
    try {
      // @ts-ignore
      const handle = await instance.encryptUInt32(Number(inputValue));
      setEncryptedHandle(handle);
    } catch (err) {
      console.error("Encryption failed:", err);
    }
  };

  // Decryption handler
  const handleDecrypt = async () => {
    if (!instance || !encryptedHandle) return;
    
    try {
      // @ts-ignore
      const value = await instance.decrypt(encryptedHandle, "0xUserAddress", (window as any).ethereum);
      setDecryptedValue(value);
    } catch (err) {
      console.error("Decryption failed:", err);
    }
  };

  return (
    <div className="universal-react-example">
      <h1>Universal FHEVM SDK React Example</h1>
      
      <div>
        <h2>FHEVM Status</h2>
        <p>Status: {status}</p>
        {error && <p>Error: {error.message}</p>}
      </div>
      
      <div>
        <h2>Encryption</h2>
        <input
          type="number"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          placeholder="Enter a number to encrypt"
          disabled={status !== "ready"}
        />
        <button
          onClick={handleEncrypt}
          disabled={status !== "ready" || !inputValue}
        >
          Encrypt
        </button>
        {encryptedHandle && (
          <div>
            <p>Encrypted Handle: {JSON.stringify(encryptedHandle)}</p>
          </div>
        )}
      </div>
      
      <div>
        <h2>Decryption</h2>
        <button
          onClick={handleDecrypt}
          disabled={status !== "ready" || !encryptedHandle}
        >
          Decrypt
        </button>
        {decryptedValue !== null && (
          <div>
            <p>Decrypted Value: {String(decryptedValue)}</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default UniversalReactExample;

// examples/universal-vue-example.vue
<!-- Universal FHEVM SDK Vue Example -->

<template>
  <div class="universal-vue-example">
    <h1>Universal FHEVM SDK Vue Example</h1>
    
    <div>
      <h2>FHEVM Status</h2>
      <p>Status: {{ status }}</p>
      <p v-if="error">Error: {{ error.message }}</p>
    </div>
    
    <div>
      <h2>Encryption</h2>
      <input
        v-model="inputValue"
        type="number"
        placeholder="Enter a number to encrypt"
        :disabled="status !== 'ready'"
      />
      <button
        @click="handleEncrypt"
        :disabled="status !== 'ready' || !inputValue"
      >
        Encrypt
      </button>
      <div v-if="encryptedHandle">
        <p>Encrypted Handle: {{ JSON.stringify(encryptedHandle) }}</p>
      </div>
    </div>
    
    <div>
      <h2>Decryption</h2>
      <button
        @click="handleDecrypt"
        :disabled="status !== 'ready' || !encryptedHandle"
      >
        Decrypt
      </button>
      <div v-if="decryptedValue !== null">
        <p>Decrypted Value: {{ String(decryptedValue) }}</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { vue } from '@fhevm-sdk/universal';

// Reactive state
const inputValue = ref<string>('');
const encryptedHandle = ref<any>(null);
const decryptedValue = ref<any>(null);

// FHEVM instance
const { instance, status, error } = vue.useUniversalFhevm({
  provider: typeof window !== 'undefined' ? (window as any).ethereum : undefined,
  chainId: 11155111, // Sepolia testnet
  enabled: true,
});

// Encryption handler
const handleEncrypt = async () => {
  if (!instance.value || !inputValue.value) return;
  
  try {
    // @ts-ignore
    const handle = await instance.value.encryptUInt32(Number(inputValue.value));
    encryptedHandle.value = handle;
  } catch (err) {
    console.error("Encryption failed:", err);
  }
};

// Decryption handler
const handleDecrypt = async () => {
  if (!instance.value || !encryptedHandle.value) return;
  
  try {
    // @ts-ignore
    const value = await instance.value.decrypt(encryptedHandle.value, "0xUserAddress", (window as any).ethereum);
    decryptedValue.value = value;
  } catch (err) {
    console.error("Decryption failed:", err);
  }
};
</script>

<style scoped>
.universal-vue-example {
  padding: 1rem;
}

input, button {
  margin: 0.5rem;
  padding: 0.5rem;
}
</style>
